# Generated by Django 5.1 on 2025-06-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='domain',
            field=models.CharField(choices=[('Frontend Developer', 'Frontend Developer'), ('Backend Developer', 'Backend Developer'), ('Full Stack Developer', 'Full Stack Developer'), ('DevOps Engineer', 'DevOps Engineer'), ('Python Developer', 'Python Developer'), ('PHP Developer', 'PHP Developer')], default='Frontend Developer', max_length=100),
        ),
    ]
