# Generated by Django 5.1 on 2025-06-22 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_resume_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='domain',
        ),
    ]
